% crystal symmetry
CS = {...
  'notIndexed',...
  crystalSymmetry('m3m', [2 2 2], 'mineral', 'Austenite', 'color', 'blue'),...
  crystalSymmetry('m3m', [3 3 3], 'mineral', 'Martensite', 'color', 'green'),...
  };
SS = specimenSymmetry('triclinic');
% plotting convention
setMTEXpref('xAxisDirection','east');
setMTEXpref('zAxisDirection','outOfPlane');
% file name
fname = 'Data/Map1.txt';
% create an EBSD variable containing the data
 ebsd = loadEBSD_generic(fname,'CS',CS,'SS',SS, 'ColumnNames', ...
      {'Index' 'Phase' 'x' 'y' 'Euler1' 'Euler2' 'Euler3' 'MAD' 'BC' 'BS'...
      'Bands' 'Error' 'ReliabilityIndex'}, 'Bunge',);

 ebsd = loadEBSD_generic(fname,'CS',CS,'SS',SS, 'ColumnNames', ...
      {'Euler1' 'Euler2' 'Euler3' 'x' 'y' 'IQ' 'CI' 'Phase'},...
      'Columns',{1,2,3,4,5,6,7,8},...
      'Bunge');


ebsd = loadEBSD(fname,CS);
%,'interface','ctf',...
%  'convertEuler2SpatialReferenceFrame');




loadEBSD_generic(ang_filename,'ColumnNames',...
    {'Euler1','Euler2','Euler3','x', 'y','IQ', 'CI','Phase'},...
    'Columns',{1,2,3,4,5,6,7,8,9})